name: haritaapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  location: ^4.4.0
  uuid: ^3.0.7
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps: ^6.2.0
  google_maps_flutter: ^2.2.6
  google_map_polyline_new: ^0.3.0+2
  google_directions_api: ^0.9.1
  http: ^0.13.6
  google_maps_webservice: ^0.0.19
  get: ^4.6.5
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/

