// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5ZNBs7Kv3hKFJx4ohFIJLOd5zMJhJYM',
    appId: '1:544148744187:web:fbf0aee7db98b87d128d5e',
    messagingSenderId: '544148744187',
    projectId: 'adsveritabani-5fbe2',
    authDomain: 'adsveritabani-5fbe2.firebaseapp.com',
    storageBucket: 'adsveritabani-5fbe2.appspot.com',
    measurementId: 'G-X63EE15YHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARs2jFFjJjRrHQ8FNW4LzRuB_6nDXPMBI',
    appId: '1:544148744187:android:cbbb7905f12b00b7128d5e',
    messagingSenderId: '544148744187',
    projectId: 'adsveritabani-5fbe2',
    storageBucket: 'adsveritabani-5fbe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOGOpeLWC3imHQGUKlCkdO13tkN3nfif4',
    appId: '1:544148744187:ios:484fd48e64e11f49128d5e',
    messagingSenderId: '544148744187',
    projectId: 'adsveritabani-5fbe2',
    storageBucket: 'adsveritabani-5fbe2.appspot.com',
    iosBundleId: 'com.example.ads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOGOpeLWC3imHQGUKlCkdO13tkN3nfif4',
    appId: '1:544148744187:ios:1c1ddef47370fbe6128d5e',
    messagingSenderId: '544148744187',
    projectId: 'adsveritabani-5fbe2',
    storageBucket: 'adsveritabani-5fbe2.appspot.com',
    iosBundleId: 'com.example.ads.RunnerTests',
  );
}
